export const BASE_PRODUCTS = [
  // Cocinas
  {
    id: "cocineta_2q_gas",
    name: "Cocineta 2Q A gas",
    category: "cocinas",
    brand: null,
    model: null,
    specs: { peso: "3kg", material: "esmaltado" },
  },
  {
    id: "mabe_cocina_4q",
    name: "Cocina Mabe 4Q",
    category: "cocinas",
    brand: "Mabe",
    model: "TX5110P2",
    specs: {
      encendido: "manual",
      horno: "gas natural",
      capacidad_horno: "63L",
      peso: "23kg",
    },
  },
  {
    id: "mabe_cocina_6q",
    name: "Cocina Mabe 6Q",
    category: "cocinas",
    brand: "Mabe",
    model: "CMP7625FX0",
    specs: { quemadores: 6 },
  },
  {
    id: "indurama_cocina_6q",
    name: "Cocina Indurama 6Q",
    category: "cocinas",
    brand: "Indurama",
    model: "PARMA",
    specs: { quemadores: 6 },
  },
  {
    id: "miray_cocina_4q",
    name: "Cocina Miray 4Q",
    category: "cocinas",
    brand: "Miray",
    model: "IRIS PLUS",
    specs: { quemadores: 4 },
  },
  {
    id: "encimera_mabe_5q",
    name: "Encimera Mabe 5Q",
    category: "cocinas",
    brand: "Mabe",
    model: "PM8655GV0",
    specs: {
      quemadores: 5,
      encendido: "eléctrico",
      material: "vidrio templado negro",
    },
  },

  // Termas
  {
    id: "terma_holi_5_5l",
    name: "Terma Holi 5.5L A gas",
    category: "termas",
    brand: "Holi",
    model: "MISTI",
    specs: {
      capacidad: "5.5L",
      color: "blanco",
      rango: "35ºC-65ºC",
      gas: "natural",
    },
  },

  // Celulares
  {
    id: "samsung_a56",
    name: "Samsung Galaxy A56",
    category: "celulares",
    brand: "Samsung",
    model: "A56",
    specs: { storage: "256GB", ram: "8GB", display: '6.7" amoled' },
  },
  {
    id: "samsung_a35",
    name: "Samsung Galaxy A35",
    category: "celulares",
    brand: "Samsung",
    model: "A35",
    specs: { storage: "256GB", ram: "8GB" },
  },
  {
    id: "samsung_a26",
    name: "Samsung Galaxy A26",
    category: "celulares",
    brand: "Samsung",
    model: "A26",
    specs: { storage: "128GB", ram: "6GB" },
  },
  {
    id: "samsung_a17_5g",
    name: "Samsung Galaxy A17 5G",
    category: "celulares",
    brand: "Samsung",
    model: "A17 5G",
    specs: {},
  },
  {
    id: "xiaomi_redmi_15c",
    name: "Xiaomi Redmi 15C",
    category: "celulares",
    brand: "Xiaomi",
    model: "Redmi 15C",
    specs: {},
  },
  {
    id: "honor_x6c",
    name: "Honor X6C",
    category: "celulares",
    brand: "Honor",
    model: "X6C",
    specs: {},
  },

  // TVs
  {
    id: "jvc_tv_43",
    name: 'Smart TV JVC 43"',
    category: "tv",
    brand: "JVC",
    model: "LT-43KM348",
    specs: {
      resolution: "FHD",
      os: "Google TV",
      connectivity: "WiFi/Bluetooth",
    },
  },
  {
    id: "jvc_tv_86",
    name: 'Smart TV JVC 86"',
    category: "tv",
    brand: "JVC",
    model: "LT-86KB738",
    specs: { size: '86"' },
  },
  {
    id: "hisense_tv_50",
    name: 'Smart TV Hisense 50"',
    category: "tv",
    brand: "Hisense",
    model: null,
    specs: { size: '50"' },
  },
  {
    id: "hisense_tv_55",
    name: 'Smart TV Hisense 55"',
    category: "tv",
    brand: "Hisense",
    model: null,
    specs: { size: '55"', control: "remoto" },
  },
  {
    id: "tcl_tv_55",
    name: 'Smart TV TCL 55"',
    category: "tv",
    brand: "TCL",
    model: null,
    specs: { size: '55"' },
  },
  {
    id: "samsung_tv_65",
    name: 'Smart TV Samsung 65"',
    category: "tv",
    brand: "Samsung",
    model: "UN65DU8000GXPE / UN65DU8200GXPE",
    specs: { size: '65"' },
  },
  {
    id: "samsung_tv_70",
    name: 'Smart TV Samsung 70"',
    category: "tv",
    brand: "Samsung",
    model: "QN70Q65DAGXPE",
    specs: { size: '70"', control_voz: true },
  },
  {
    id: "lg_tv_65",
    name: 'Smart TV LG 65"',
    category: "tv",
    brand: "LG",
    model: "65UA7300PSB",
    specs: { size: '65"' },
  },

  // Refrigeradoras
  {
    id: "mabe_refri_187l",
    name: "Refrigeradora Mabe 187L",
    category: "refrigeradoras",
    brand: "Mabe",
    model: "RMU202PXPRS1",
    specs: { capacidad: "187L", tipo: "monopuerta", acabado: "inoxidable" },
  },
  {
    id: "mabe_refri_230l",
    name: "Refrigeradora Mabe 230L",
    category: "refrigeradoras",
    brand: "Mabe",
    model: null,
    specs: {
      capacidad: "230L",
      tipo: "congelador superior",
      dispensador: "agua",
    },
  },
  {
    id: "mabe_refri_239l",
    name: "Refrigeradora Mabe 239L",
    category: "refrigeradoras",
    brand: "Mabe",
    model: "RMA255FYPG",
    specs: {
      capacidad: "239L",
      tipo: "congelador superior",
      dispensador: "agua",
      parillas: 3,
    },
  },
  {
    id: "mabe_refri_511l",
    name: "Refrigeradora Mabe 511L",
    category: "refrigeradoras",
    brand: "Mabe",
    model: "MSD518LKRSS0",
    specs: { capacidad: "511L" },
  },
  {
    id: "lg_refri_509l",
    name: "Refrigeradora LG 509L",
    category: "refrigeradoras",
    brand: "LG",
    model: "GS51MPD",
    specs: { capacidad: "509L" },
  },
  {
    id: "indurama_refri_508l",
    name: "Refrigeradora Indurama 508L",
    category: "refrigeradoras",
    brand: "Indurama",
    model: "RI-788DI",
    specs: { capacidad: "508L" },
  },
  {
    id: "electrolux_refri_514l",
    name: "Refrigerador Electrolux 514L",
    category: "refrigeradoras",
    brand: "Electrolux",
    model: "ERSA53K2HVB",
    specs: { capacidad: "514L" },
  },
  {
    id: "lg_refri_314l",
    name: "Refrigerador LG 314L",
    category: "refrigeradoras",
    brand: "LG",
    model: "GT31WPP",
    specs: { capacidad: "314L" },
  },

  // Lavadoras
  {
    id: "mabe_lavadora_9kg",
    name: "Lavadora Mabe 9kg",
    category: "lavadoras",
    brand: "Mabe",
    model: null,
    specs: { capacidad: "9kg" },
  },
  {
    id: "mabe_lavadora_10kg",
    name: "Lavadora Mabe 10kg",
    category: "lavadoras",
    brand: "Mabe",
    model: "LMAP1010WBBB0",
    specs: { capacidad: "10kg" },
  },
  {
    id: "mabe_lavadora_16kg",
    name: "Lavadora Mabe 16kg",
    category: "lavadoras",
    brand: "Mabe",
    model: "LMAP6115WGBB0",
    specs: { capacidad: "16kg", color: "silver", carga: "superior" },
  },
  {
    id: "mabe_lavadora_22kg",
    name: "Lavadora Mabe 22kg",
    category: "lavadoras",
    brand: "Mabe",
    model: "LMA722000WDBB2",
    specs: { capacidad: "22kg" },
  },
  {
    id: "lg_lavadora_19kg",
    name: "Lavadora LG 19kg",
    category: "lavadoras",
    brand: "LG",
    model: "WT19BVTB",
    specs: { capacidad: "19kg" },
  },
  {
    id: "lavaseca_samsung",
    name: "Lavaseca Samsung",
    category: "lavadoras",
    brand: "Samsung",
    model: "WD11T4046BX",
    specs: { lavado: "11kg", secado: "7kg" },
  },
  {
    id: "lg_lavadora_16kg",
    name: "Lavadora LG 16kg",
    category: "lavadoras",
    brand: "LG",
    model: "WT16BVTB",
    specs: { capacidad: "16kg", color: "negro", panel: "LED" },
  },
  {
    id: "samsung_lavadora_13kg",
    name: "Lavadora Samsung 13kg",
    category: "lavadoras",
    brand: "Samsung",
    model: "WA13CG5441BDPE",
    specs: { capacidad: "13kg" },
  },
  {
    id: "lavaseca_lg_samsung",
    name: "Lavaseca LG/Samsung",
    category: "lavadoras",
    brand: null,
    model: null,
    specs: { lavado: "11kg", secado: "7kg" },
  },

  // Audio
  {
    id: "samsung_torre_sonido",
    name: "Torre de sonido Samsung",
    category: "audio",
    brand: "Samsung",
    model: "MX-T50/PE",
    specs: {},
  },
  {
    id: "lg_torre_sonido",
    name: "Torre de sonido LG",
    category: "audio",
    brand: "LG",
    model: "RNC9",
    specs: { microfono: true },
  },
  {
    id: "samsung_barra_sonido",
    name: "Barra de sonido Samsung",
    category: "audio",
    brand: "Samsung",
    model: "HW-C400/PE",
    specs: {},
  },

  // Pequeños electrodomésticos
  {
    id: "licuadora",
    name: "Licuadora",
    category: "pequeños",
    brand: null,
    model: null,
    specs: {},
  },
  {
    id: "exprimidor",
    name: "Exprimidor",
    category: "pequeños",
    brand: null,
    model: null,
    specs: {},
  },

  {
    id: "samsung_a36",
    name: "Samsung Galaxy A36",
    category: "celulares",
    brand: "Samsung",
    model: "A36",
    specs: { storage: "128GB", ram: "6GB" },
  },
  {
    id: "samsung_s22",
    name: "Samsung Galaxy S22",
    category: "celulares",
    brand: "Samsung",
    model: "S22",
    specs: { storage: "128GB", ram: "8GB" },
  },
  {
    id: "xiaomi_note_14_pro",
    name: "Xiaomi Redmi Note 14 Pro",
    category: "celulares",
    brand: "Xiaomi",
    model: "Redmi Note 14 Pro",
    specs: { storage: "256GB", ram: "8GB" },
  },
  {
    id: "iphone_13",
    name: "iPhone 13",
    category: "celulares",
    brand: "Apple",
    model: "iPhone 13",
    specs: { storage: "128GB", ram: "4GB" },
  },
  {
    id: "iphone_15",
    name: "iPhone 15",
    category: "celulares",
    brand: "Apple",
    model: "iPhone 15",
    specs: { storage: "128GB", ram: "6GB" },
  },
  {
    id: "iphone_16",
    name: "iPhone 16",
    category: "celulares",
    brand: "Apple",
    model: "iPhone 16",
    specs: { storage: "128GB", ram: "8GB" },
  },
  {
    id: "iphone_16_pro",
    name: "iPhone 16 Pro",
    category: "celulares",
    brand: "Apple",
    model: "iPhone 16 Pro",
    specs: { storage: "256GB", ram: "8GB" },
  },

  // Laptops
  {
    id: "laptop_lenovo_i7",
    name: "Laptop Lenovo i7",
    category: "laptops",
    brand: "Lenovo",
    model: "IdeaPad Slim 5i",
    specs: { processor: "i7" },
  },
  {
    id: "laptop_acer_i5",
    name: "Laptop Acer i5",
    category: "laptops",
    brand: "Acer",
    model: "AL15-71P-53N7",
    specs: { processor: "i5" },
  },
] as const;

export type BaseProductId = (typeof BASE_PRODUCTS)[number]["id"];
