generate_env_file() {
	local file="$1"

	cat >"$file" <<EOF
NODE_ENV=production
LOG_LEVEL=info
PORT=3000
NOTIFIER_PORT=3001
FRONTEND_URL=http://localhost:5173
DB_PATH=./data/database.sqlite
UPLOAD_DIR=./data/uploads
JWT_SECRET=$JWT_SECRET
PUBLIC_URL=$PUBLIC_URL
NOTIFIER_URL=http://localhost:3001
NOTIFIER_DATA_PATH=./data/notifier
BACKEND_URL=http://localhost:3000
${WHATSAPP_GROUP_AGENT:+WHATSAPP_GROUP_AGENT=$WHATSAPP_GROUP_AGENT}
${WHATSAPP_GROUP_DEV:+WHATSAPP_GROUP_DEV=$WHATSAPP_GROUP_DEV}
WHATSAPP_TOKEN=$WHATSAPP_TOKEN
WHATSAPP_PHONE_ID=$WHATSAPP_PHONE_ID
WHATSAPP_WEBHOOK_VERIFY_TOKEN=$WHATSAPP_WEBHOOK_VERIFY_TOKEN
CALIDDA_BASE_URL=https://appweb.calidda.com.pe
CALIDDA_USERNAME=$CALIDDA_USERNAME
CALIDDA_PASSWORD=$CALIDDA_PASSWORD
POWERBI_RESOURCE_KEY=$POWERBI_RESOURCE_KEY
POWERBI_REPORT_ID=$POWERBI_REPORT_ID
POWERBI_DATASET_ID=$POWERBI_DATASET_ID
POWERBI_MODEL_ID=$POWERBI_MODEL_ID
${GEMINI_API_KEY:+GEMINI_API_KEY=$GEMINI_API_KEY}
EOF
}
